"""GitHub issue creation via `gh` CLI."""

from __future__ import annotations

import logging
import subprocess
from datetime import UTC, datetime

from tentacle.models import Analysis, Article, Issue

logger = logging.getLogger(__name__)


def create_issue(
    article: Article,
    analysis: Analysis,
    *,
    repo: str,
    label: str,
    dry_run: bool = False,
) -> Issue | None:
    """Create a GitHub issue from an analysis. Returns Issue or None on failure."""
    if not analysis.suggested_title or not analysis.suggested_body:
        logger.warning("Analysis missing title or body for article '%s'", article.title[:60])
        return None

    title = analysis.suggested_title
    body = _format_body(article, analysis)

    if dry_run:
        logger.info("DRY RUN: would create issue '%s'", title)
        return None

    try:
        result = subprocess.run(
            [
                "gh",
                "issue",
                "create",
                "--repo",
                repo,
                "--title",
                title,
                "--body",
                body,
                "--label",
                label,
            ],
            capture_output=True,
            text=True,
            timeout=30,
        )
    except (subprocess.TimeoutExpired, FileNotFoundError):
        logger.exception("Failed to create issue")
        return None

    if result.returncode != 0:
        logger.warning("gh issue create failed: %s", result.stderr[:200])
        return None

    # Parse issue URL and number from output
    issue_url = result.stdout.strip()
    try:
        issue_number = int(issue_url.rsplit("/", 1)[-1])
    except ValueError:
        logger.warning("Could not parse issue number from: %s", issue_url)
        return None

    logger.info("Created issue #%d: %s", issue_number, title)

    analysis_id = analysis.id if analysis.id is not None else 0
    return Issue(
        article_id=article.id,
        analysis_id=analysis_id,
        github_number=issue_number,
        github_url=issue_url,
        title=title,
        created_at=datetime.now(UTC),
        maturity_score=analysis.maturity_score,
        current_maturity=analysis.maturity_score,
    )


def _format_body(article: Article, analysis: Analysis) -> str:
    """Format the issue body with source attribution and maturity tag."""
    body = analysis.suggested_body or ""

    # Ensure source section exists
    if "## Source" not in body:
        authors = ", ".join(article.authors) if article.authors else "Unknown"
        published = article.published_at.strftime("%Y-%m-%d") if article.published_at else "Unknown"
        body += f"""

## Source
- **Paper/Article:** [{article.title}]({article.url})
- **Authors:** {authors}
- **Published:** {published}
- **Relevance Score:** {analysis.relevance_score:.2f}
- **Maturity:** {analysis.maturity_score}/5"""

    body += f"""

---
*Generated by tentacle. Maturity {analysis.maturity_score}/5.*"""

    return body
